apps/dashboards/urls.py
from django.urls import path

from apps.users import views as users_views
from apps.dashboards import views as dashboard_views


app_name = 'dashboards'

urlpatterns = [
    path('', dashboard_views.DashboardView.as_view(), name='dashboard'),
    path('login', users_views.Login.as_view(), name='login'),
]

apps/users/urls.py
from django.urls import path

from apps.users.views import (UserListView)

urlpatterns = [
    path('list', UserListView.as_view(), name='users-list'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('apps.users.urls')),
]
urlpatterns += path('', include('apps.dashboards.urls')),
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/common/models.py
from django.db import models


class ActiveManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_archived=False)


class BaseModel(models.Model):
    is_archived = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ActiveManager()
    all_objects = models.Manager()

    class Meta:
        abstract = True

apps/orders/models.py
import uuid

from django.db import models

from apps.common.models import BaseModel


class Order(BaseModel):
    PAYMENT_METHOD_CHOICES = [
        ('ONLINE', 'Online'),
        ('COD', 'Cash on Delivery'),
    ]
    DELIVERY_STATUS_CHOICES = [
        ('PRODUCT_DISPATCHED', 'Product Dispatched'),
        ('PRODUCT_DELIVERED', 'Product Delivered'),
        ('ON_ROUTE', 'On Route'),
        ('UNKNOWN', 'Unknown'),
        ('CANCELLED', 'Cancelled'),
        ('RECEIVER_FAILED', 'Receiver Failed'),
    ]
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    order_id = models.CharField(max_length=255, unique=True)
    payment_id = models.CharField(max_length=255, null=True, blank=True)
    payment_status = models.BooleanField(default=False)
    amount_to_receive = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    payment_method = models.CharField(max_length=255, choices=PAYMENT_METHOD_CHOICES)
    delivery_status = models.CharField(max_length=255, choices=DELIVERY_STATUS_CHOICES, null=True, blank=True)

    customer_name = models.CharField(max_length=255)
    customer_phone = models.CharField(max_length=15, null=True, blank=True)
    customer_secondary_phone = models.CharField(max_length=15, null=True, blank=True)
    customer_email = models.EmailField(null=True, blank=True)

    delivery_address = models.TextField()
    delivery_city = models.CharField(max_length=100)
    delivery_state = models.CharField(max_length=100)
    delivery_zip_code = models.CharField(max_length=20)

    expected_delivery_date = models.DateTimeField(null=True, blank=True)
    actual_delivery_date = models.DateTimeField(null=True, blank=True)

    delivery_person = models.CharField(max_length=255, null=True, blank=True)
    delivery_person_contact = models.CharField(max_length=15, null=True, blank=True)

    delivery_instructions = models.TextField(null=True, blank=True)
    order_notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.order_id

apps/support/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from apps.users.manager import CustomUserManager
from apps.users.choices import UserRole
from apps.common.models import BaseModel


class User(AbstractBaseUser, PermissionsMixin, BaseModel):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        validators=[RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')],
        blank=True,
        null=True
    )
    full_name = models.CharField(_('full name'), max_length=255, blank=True)
    role = models.CharField(max_length=2, choices=UserRole.choices, default=UserRole.STAFF)
    is_active = models.BooleanField(_('active'), default=True)
    is_staff = models.BooleanField(_('staff status'), default=False)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    is_verified = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    @property
    def is_superadmin(self):
        return self.role == UserRole.SUPERADMIN

    @property
    def is_admin(self):
        return self.role == UserRole.ADMIN

    @property
    def is_delivery_boy(self):
        return self.role == UserRole.DELIVERY_BOY

    @property
    def is_regular_staff(self):
        return self.role == UserRole.STAFF


class SuperadminManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role=UserRole.SUPERADMIN)


class AdminManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role=UserRole.ADMIN)


class DeliveryBoyManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role=UserRole.DELIVERY_BOY)


class StaffManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role=UserRole.STAFF)


User.superadmins = SuperadminManager()
User.admins = AdminManager()
User.delivery_boys = DeliveryBoyManager()
User.staff = StaffManager()

apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate, login


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=254, label='Email')
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if email and password:
            user = authenticate(username=email, password=password)
            if user is None:
                raise forms.ValidationError("Email or password did not match.")
            if not user.is_active or not user.is_staff or not user.is_verified:
                raise forms.ValidationError('User is not active or you do not have permission.')
            cleaned_data['user'] = user
        return cleaned_data

apps/dashboards/views.py
from django.views.generic import TemplateView,ListView

from apps.users.mixins import AuthMixin


class DashboardView(AuthMixin, TemplateView):
    template_name = 'dashboards/index.html'
    menu_active = 'dashboards'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

apps/support/views.py
from django.shortcuts import render

# Create your views here.

apps/users/views.py
from django.contrib.auth import get_user_model
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, FormView

from apps.users.mixins import LoginMixin, AuthMixin, PermissionRequiredMixin
from apps.users import forms

User = get_user_model()


class Login(LoginMixin):
    template_name = 'account/login.html'
    form_class = forms.LoginForm

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class UserListView(AuthMixin, PermissionRequiredMixin, ListView):
    permission_required = 'users.view_user'
    paginate_by = 15
    template_name = 'users/list.html'
    model = User
    context_object_name = 'users'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        page_number = self.request.GET.get('page', 1)
        items_per_page = 15
        context['page_index'] = (int(page_number)-1)*items_per_page
        context['names'] = User.all_objects.all()
        return context

    def get_queryset(self):
        name = self.request.GET.get('name')
        role = self.request.GET.get('role')
        queryset = User.all_objects.all()
        if name:
            queryset = queryset.filter(name__icontains=name)
        if role:
            queryset = queryset.filter(role__icontains=role)
        return queryset

templates/dashboards/index.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block extra_css %}
    <!-- jsvectormap css -->
    <link href="{% static 'libs/jsvectormap/dist/css/jsvectormap.min.css'%}" rel="stylesheet" type="text/css" />

    <!--Swiper slider css-->
    <link href="{% static 'libs/swiper/swiper-bundle.min.css'%}" rel="stylesheet" type="text/css" />
{% endblock extra_css %}

{% block content %}
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">

                    <div class="row">
                        <div class="col">



                        </div> <!-- end col -->
                            <div class="px-4">
                            <div class="row">
                                <div class="col-xxl-5 align-self-center">
                                    <div class="py-4">
                                        <h4 class="display-6 coming-soon-text">Welcome to Quick-Cart delivery service.</h4>
                                        <p class="text-muted fs-15 mt-3">The best product delivery service, manage and hosted by Quick-Cart.</p>
                                    </div>
                                </div>
                                <div class="col-xxl-3 ms-auto">
                                    <div class="mb-n5 pb-1 faq-img d-none d-xxl-block">
                                        <img src="{% static 'images/faq-img.png'%}" alt="" class="img-fluid">
                                    </div>
                                </div>
                            </div>

                    </div>

                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->
            {% block footer %}
            {% include "partials/footer.html" %}
            {% endblock footer %}

        </div>
        <!-- end main content-->
{% endblock content %}

{% block extra_js %}
<!-- apexcharts -->
<script src="{% static 'libs/apexcharts/dist/apexcharts.min.js'%}"></script>

<!-- Vector map-->
<script src="{% static 'libs/jsvectormap/dist/js/jsvectormap.min.js'%}"></script>
<script src="{% static 'libs/jsvectormap/dist/maps/world-merc.js'%}"></script>

<!--Swiper slider js-->
<script src="{% static 'libs/swiper/swiper-bundle.min.js'%}"></script>

<!-- Dashboard init -->
<script src="{% static 'js/pages/dashboard-ecommerce.init.js'%}"></script>
{% endblock extra_js %}

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" {% block html %}data-layout="vertical" data-topbar="light" data-sidebar="dark" data-sidebar-size="sm-hover" data-sidebar-image="none" data-preloader="disable" {% endblock html %}>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock title %} | Velzon - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico'%}">

    {% block css %}
    {% block extra_css %}
    {% endblock extra_css %}

    <!-- Layout config Js -->
    <script src="{% static 'js/layout.js'%}"></script>
    <!-- Bootstrap Css -->
    <link href="{% static 'css/bootstrap.min.css'%}" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="{% static 'css/icons.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="{% static 'css/app.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    <!-- custom Css-->
    <link href="{% static 'css/custom.min.css'%}" id="app-style" rel="stylesheet" type="text/css" />
    {% endblock css %}
</head>

<body>
    <!-- Begin page -->
    <div id="layout-wrapper">
        {% block header %}
        {% include "partials/topbar.html" %}
        {% endblock header %}
        {% block sidebar %}
        {% include "partials/sidebar.html" %}
        {% endblock sidebar %}
        {% block content %}
        {% block pagetitle %}
        {% endblock pagetitle %}
        {% block footer %}
        {% endblock footer %}
        {% endblock content %}
    </div>

    {% block extra_content %}
    {% endblock extra_content %}

    <!-- END layout-wrapper -->
    {% block right_sidebar %}
    {% include "partials/customizer.html" %}
    {% endblock right_sidebar %}

    {% block javascript %}
    <!-- JAVASCRIPT -->
    <script src="{% static 'libs/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'libs/simplebar/dist/simplebar.min.js'%}"></script>
    <script src="{% static 'libs/node-waves/dist/waves.min.js'%}"></script>
    <script src="{% static 'libs/feather-icons/dist/feather.min.js'%}"></script>
    <script src="{% static 'js/pages/plugins/lord-icon-2.1.0.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>

    {% block extra_js %}
    {% endblock extra_js %}

    <!-- App js -->
    <script src="{% static 'js/app.js'%}"></script>
    {% endblock javascript %}

</body>

</html>

templates/partials/footer.html
{% block footer %}
            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © Quick-Cart.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
                                Design & Develop by Sudarshan.
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
{% endblock footer %}

templates/partials/page-title.html
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0">{{title}}</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">{{pagetitle}}</a></li>
                    <li class="breadcrumb-item active">{{title}}</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

templates/partials/sidebar.html
{% load static %}
{% block sidebar %}
        <!-- ========== App Menu ========== -->
        <div class="app-menu navbar-menu">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <!-- Dark Logo-->
                <a href="{% url 'dashboards:dashboard'%}" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm.png'%}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-dark.png'%}" alt="" height="17">
                    </span>
                </a>
                <!-- Light Logo-->
                <a href="{% url 'dashboards:dashboard'%}" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm.png'%}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-light.png'%}" alt="" height="17">
                    </span>
                </a>
                <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover" id="vertical-hover">
                    <i class="ri-record-circle-line"></i>
                </button>
            </div>

            <div id="scrollbar">
                <div class="container-fluid">

                    <div id="two-column-menu">
                    </div>
                    <ul class="navbar-nav" id="navbar-nav">
                        <li class="menu-title"><span data-key="t-menu">Menu</span></li>
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarDashboards" data-bs-toggle="collapse" role="button"
                                aria-expanded="false" aria-controls="sidebarDashboards">
                                <i class="las la-tachometer-alt"></i> <span data-key="t-dashboards">Dashboards</span>
                            </a>
                            <div class="collapse menu-dropdown" id="sidebarDashboards">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="{% url 'dashboards:dashboard' %}" class="nav-link" data-key="t-analytics"> Analytics </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'dashboards:dashboard' %}" class="nav-link" data-key="t-crm"> CRM </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'dashboards:dashboard' %}" class="nav-link" data-key="t-ecommerce"> Ecommerce </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'dashboards:dashboard' %}" class="nav-link" data-key="t-crypto"> Crypto </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'dashboards:dashboard' %}" class="nav-link" data-key="t-projects"> Projects </a>
                                    </li>
                                   <li class="nav-item">
                                        <a href="{% url 'dashboards:dashboard' %}" class="nav-link" data-key="t-nft"> NFT </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url 'dashboards:dashboard' %}" class="nav-link" data-key="t-job">Job</a>
                                    </li>
                                </ul>
                            </div>
                        </li> <!-- end Dashboard Menu -->
                        <li class="nav-item">
                            <a class="nav-link menu-link" href="#sidebarApps" data-bs-toggle="collapse"
                                role="button" aria-expanded="false" aria-controls="sidebarApps">
                                <i class="lab la-delicious"></i> <span data-key="t-apps">Apps</span>
                            </a>
                            <div class="collapse menu-dropdown" id="sidebarApps">
                                <ul class="nav nav-sm flex-column">
                                    <li class="nav-item">
                                        <a href="#sidebarCalendar" class="nav-link" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarCalendar" data-key="t-calender">
                                            Calendar
                                        </a>
                                        <div class="collapse menu-dropdown" id="sidebarCalendar">
                                            <ul class="nav nav-sm flex-column">
                                                <li class="nav-item">
                                                    <a href="{% url 'dashboards:dashboard'%}" class="nav-link" data-key="t-main-calender"> Main Calender </a>
                                                </li>
                                                <li class="nav-item">
                                                    <a href="{% url 'dashboards:dashboard'%}" class="nav-link" data-key="t-month-grid"> Month Grid </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </li>

                    </ul>
                </div>
                <!-- Sidebar -->
            </div>
            <div class="sidebar-background"></div>
        </div>
        <!-- Left Sidebar End -->
        <!-- Vertical Overlay-->
        <div class="vertical-overlay"></div>
{% endblock sidebar %}

templates/users/list.html
{% extends "partials/base.html" %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block extra_css %}
    <!-- jsvectormap css -->
    <link href="{% static 'libs/jsvectormap/dist/css/jsvectormap.min.css'%}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/sweetalert2/dist/sweetalert2.min.css' %}" rel="stylesheet" type="text/css" />

    <!--Swiper slider css-->
    <link href="{% static 'libs/swiper/swiper-bundle.min.css'%}" rel="stylesheet" type="text/css" />
{% endblock extra_css %}

{% block content %}
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">
                {% block page-title %}
                {% include "partials/page-title.html" with page_title="Base UI" title="User list" %}
                {% endblock page-title %}

                    <div class="row">
                        <!-- Striped Rows -->
                        <div class="col-lg-12">
                            <div class="col-md-auto ms-auto">
                                <div class="d-flex gap-2">
                                    <div class="search-box">
                                        <input type="text" class="form-control search" placeholder="Search for users...">
                                        <i class="ri-search-line search-icon"></i>
                                    </div>
                                    <button class="btn btn-success"><i class="ri-equalizer-line align-bottom me-1"></i> Filters</button>
                                </div>
                            </div><!--end col-->
                            <div class="noresult" style="display: none">
                                <div class="text-center">
                                    <lord-icon src="https://cdn.lordicon.com/msoeawqm.json" trigger="loop" colors="primary:#121331,secondary:#08a88a" style="width:75px;height:75px"></lord-icon>
                                    <h5 class="mt-2">Sorry! No Result Found</h5>
                                    <p class="text-muted mb-0">We've searched more than 150+ API Keys We did not find any API for you search.</p>
                                </div>
                            </div>
                            <div class="card">
                                <div class="card-header align-items-center d-flex">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">Id</th>
                                        <th scope="col">Customer</th>
                                        <th scope="col">Date</th>
                                        <th scope="col">Invoice</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row">1</th>
                                        <td>Bobby Davis</td>
                                        <td>Nov 14, 2021</td>
                                        <td>$2,410</td>
                                        <td><span class="badge bg-success">Confirmed</span></td>
                                    </tr>
                                    <tr>
                                        <th scope="row">2</th>
                                        <td>Christopher Neal</td>
                                        <td>Nov 21, 2021</td>
                                        <td>$1,450</td>
                                        <td><span class="badge bg-warning">Waiting</span></td>
                                    </tr>
                                    <tr>
                                        <th scope="row">3</th>
                                        <td>Monkey Karry</td>
                                        <td>Nov 24, 2021</td>
                                        <td>$3,500</td>
                                        <td><span class="badge bg-success">Confirmed</span></td>
                                    </tr>
                                    <tr>
                                        <th scope="row">4</th>
                                        <td>Aaron James</td>
                                        <td>Nov 25, 2021</td>
                                        <td>$6,875</td>
                                        <td><span class="badge bg-danger">Cancelled</span></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->
            {% block footer %}
            {% include "partials/footer.html" %}
            {% endblock footer %}

        </div>

        <!-- end main content-->
{% endblock content %}

{% block extra_js %}
<!-- apexcharts -->
<script src="{% static 'libs/apexcharts/dist/apexcharts.min.js'%}"></script>

<!-- Vector map-->
<script src="{% static 'libs/jsvectormap/dist/js/jsvectormap.min.js'%}"></script>
<script src="{% static 'libs/jsvectormap/dist/maps/world-merc.js'%}"></script>

<!--Swiper slider js-->
<script src="{% static 'libs/swiper/swiper-bundle.min.js'%}"></script>

<!-- Dashboard init -->
<script src="{% static 'js/pages/dashboard-ecommerce.init.js'%}"></script>
{% endblock extra_js %}